API_TITLE: SLN SERVER API
API_VERSION: v1

# openapi.json version and URL prefix
OPENAPI_VERSION: 3.0.3
OPENAPI_URL_PREFIX: /

# Enable swagger UI
OPENAPI_SWAGGER_UI_PATH: /docs
OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist/

# MONGO CONFIG
MONGO_STR_DEV: mongodb://tal:tal@0.0.0.0:27017 # Docker in local 
MONGO_STR: mongodb://tal:tal@mongodb:27017 # Docker container in docker compose
MONGO_DB_NAME: database_test
MONGO_BAND_STATUS_COLLECTION_NAME: band_status
MONGO_BOX_TRAFFIC_COLLECTION_NAME: box_traffic
MONGO_STATIONS_TRAFFIC_COLLECTION_NAME: stations_traffic
MONGO_BOX_COUNTERS_COLLECTION_NAME: box_counters
MONGO_STATIONS_COUNTERS_COLLECTION_NAME: stations_counters
MONGO_INFERENCES_COLLECTION_NAME: inferences
MONGO_STATIONS_RTD_COLLECTION_NAME: stations_rtd

# RTD CONFIG
RTD_STATIONS: 
  - mac: 78:AF:08:31:B1:18 #PC
    ip: 192.168.102.98  
  - mac: 6C:C7:EC:2B:2E:D7 #GALAXY
    ip: 192.168.102.99
  - mac: E4:5F:01:E8:C1:2E # RPI
    ip: 192.168.102.97    
    
RTD_PERIOD_IN_SECS: 5